name: bmcs_env
channels:
- conda-forge
dependencies:
- appmode
- jupyter_contrib_nbextensions
- traits
- matplotlib-base
- numpy
- scipy
- sympy
- ipywidgets
- ipympl
- pip
- pip:
  - -e .
  - bmcs-utils
  - bmcs-ibvpy
  - bmcs-matmod